booking/urls.py
from django.urls import path
from . import views
app_name = 'booking'
urlpatterns = [
    path("", views.services, name="services"),
    path("booking/<int:service_id>", views.booking, name="booking"),
    path('api/get_available_slots/', views.available_times, name="get_available_slots"),
    path("api/create_booking/", views.create_booking, name="create_booking"),
    # path("api/available_dates/", views.AvailableDatesView.as_view(), name="available_dates"),
    # path("api/available_times/", views.AvailableTimesView.as_view(), name="available_times"),
    # path("api/book_session/", views.CreateBookingView.as_view(), name="book_session"),
]

pt_presentation/urls.py
from django.urls import path, include
from . import views

app_name="pt_presentation"
urlpatterns = [
    path("hjem/", views.hjem, name="hjem"),
    path("om-meg/", views.om_meg, name="om_meg"),
    path("blog/", views.blog, name="blog"),
    path("ernaering/", views.ernæring, name="ernaering"),
    path("treningsfilosofi/", views.treningsfilosofi, name="treningsfilosofi"),
    # path("appointment/", include("appointment.urls")),
]

pt_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pt_presentation/', include("pt_presentation.urls"), name="pt_presentation" ),
    # path('appointment/', include('appointment.urls'), name="appointment"),
    path('booking/', include('booking.urls'), name="booking"),
]

pt_presentation/models.py
from django.db import models

# Create your models here.

pt_presentation/views.py
from django.shortcuts import render
from django.http import HttpResponse

# navbarContent = [
#     {"url_name":"hjem", "display_name": "Hjem"},
#     {"url_name":"om_meg", "display_name": "Om meg"},
#     {"url_name":"blog", "display_name": "Blog"},
#     {"url_name":"treningsfilosofi", "display_name": "Treningsfilosofi"},
#     {"url_name":"ernaering", "display_name": "Ernæring"},
#     ]

navbarContent = [
    {"url_name": "pt_presentation:hjem", "base_name": "hjem", "display_name": "Hjem"},
    {"url_name": "pt_presentation:om_meg", "base_name": "om_meg", "display_name": "Om meg"},
    {"url_name": "pt_presentation:blog", "base_name": "blog", "display_name": "Blog"},
    {"url_name": "pt_presentation:treningsfilosofi", "base_name": "treningsfilosofi", "display_name": "Treningsfilosofi"},
    {"url_name": "pt_presentation:ernaering", "base_name": "ernaering", "display_name": "Ernæring"},
]

def hjem(request):
    return render(request, "frontpage/hjem.html", {
        "navbarContent": navbarContent
    })

def om_meg(request):
    return render(request, "frontpage/om_meg.html", {
        "navbarContent": navbarContent
    })

def blog(request):
    return render(request, "frontpage/blog.html", {
        "navbarContent": navbarContent
    })

def treningsfilosofi(request):
    return render(request, "frontpage/treningsfilosofi.html", {
        "navbarContent": navbarContent
    })

def ernæring(request):
    return render(request, "frontpage/ernaering.html", {
        "navbarContent": navbarContent
    })

pt_presentation/templates/frontpage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hello</title>
        <link href="{% static 'frontpage/styles.css' %}" rel="stylesheet">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    </head>
    <body>
        <header class="header">

            <a href="{% url 'pt_presentation:hjem' %}" class="logo"><span>Åsm</span>und</a>

            <nav class="navbar">
                {% for navb in navbarContent %}
                    {% url navb.url_name as nav_url %}

                    <a href="{% url navb.url_name %}" class="{% if request.resolver_match.url_name == navb.base_name %}active{% endif %}">
                        {{ navb.display_name }}
                    </a>                
                {% endfor %}
            </nav>
        
            <a href="{% url 'booking:services' %}" class="services">Book time</a>
        </header>

        {% block body %}
        {% endblock %}

    </body>
</html>

pt_presentation/templates/frontpage/blog.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
    <section class="blog">
        <h1>blog</h1>
    </section>
    
{% endblock %}

pt_presentation/templates/frontpage/ernaering.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
    <section class="ernaering">
        <h1>ernæring</h1>
    </section>
{% endblock %}

pt_presentation/templates/frontpage/hjem.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
    <section class="home">
        <div class="home-content">
            <!-- <h3>Hei</h3> -->
            <h1>Bli en skikkelig <span>O2-snapper</span> i dag!</h1>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero qui corrupti consectetur, veniam odit nesciunt aliquid fuga in quas culpa dolorem ab ipsum eum voluptas magnam quos natus numquam quo?
            </p>
            <div class="btn-box">
                <button class="btn-1">Book time</button>
                <button class="btn-2">Min Treningsfilosofi</button>
            </div>
        </div>
        <div class="img-box">
            <img src="{% static 'frontpage/asmund.jpeg' %}" alt="frontpage-picture">
        </div>
    </section>
{% endblock %}

pt_presentation/templates/frontpage/om_meg.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
    <section class="home">
        <h1>om meg</h1>
    </section>
    
{% endblock %}

pt_presentation/templates/frontpage/treningsfilosofi.html
{% extends "./base.html" %}
{% load static %}

{% block body %}
    <section class="filosofi">
        <h1>filosofi</h1>
    </section>
    
{% endblock %}